### PR TITLE
Issue 5 - Handle no connectivity

### PR DESCRIPTION
**Pull request by EmanueleC**
See #5 

All calls to the server are checked with the method `public boolean checkConnection(Context context)` in `QuizFightApplication`. If there is no connectivity, a toast message is shown to the user.

There are 2 others calls that need connectivity (facebook login and loading the friend list), which are also checked with the same method.

### CODE REVIEW

**Comment by mdipirro** [comment]
The messages seem fine to me, at a first glance trying the navigation without connectivity. The method seems correct too.

**Comment by mdipirro** [comment]
@EmanueleC I think you can merge once you solve the conflicts

**Comment by mdipirro** [comment]
It still has a conflict in `onFailure`

**Comment by EmanueleC** [comment]
Oh, yes I must have missed it

**Comment by EmanueleC** [comment]
The conflict has been resolved

**Pull request merged**
